[2022-03-21 09:58:34,307] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 09:58:34,324] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 09:58:34,324] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 09:58:34,325] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2022-03-21 09:58:34,325] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 09:58:34,339] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): dowload_desc> on 2022-03-20T00:00:00+00:00
[2022-03-21 09:58:34,342] {standard_task_runner.py:52} INFO - Started process 1163 to run task
[2022-03-21 09:58:34,346] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'dowload_desc', '2022-03-20T00:00:00+00:00', '--job-id', '511', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpfoh_7wlz', '--error-file', '/tmp/tmpc1w3as4s']
[2022-03-21 09:58:34,346] {standard_task_runner.py:77} INFO - Job 511: Subtask dowload_desc
[2022-03-21 09:58:34,392] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.dowload_desc 2022-03-20T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-21 09:58:34,437] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=dowload_desc
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-21 09:58:34,438] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 09:58:34,438] {bash.py:158} INFO - Running command: curl -o tmp_2022-03-20_2022-03-21/news_nvidia.json https://newsapi.org/v2/everything -G -d from=2022-03-20 -d to=2022-03-21 -d language=en -d q=nvidia -d apiKey=1ddd1951b81c4e9eb662cc118c33ff6a
[2022-03-21 09:58:34,446] {bash.py:169} INFO - Output:
[2022-03-21 09:58:34,454] {bash.py:173} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-03-21 09:58:34,454] {bash.py:173} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-03-21 09:58:34,754] {bash.py:173} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file tmp_2022-03-20_2022-03-21/news_nvidia.json:
[2022-03-21 09:58:34,754] {bash.py:173} INFO - Warning: No such file or directory
[2022-03-21 09:58:34,755] {bash.py:173} INFO -   5 17077    5   863    0     0   2876      0  0:00:05 --:--:--  0:00:05  2867
[2022-03-21 09:58:34,755] {bash.py:173} INFO - curl: (23) Failed writing body (0 != 863)
[2022-03-21 09:58:34,757] {bash.py:177} INFO - Command exited with return code 23
[2022-03-21 09:58:34,780] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-21 09:58:34,783] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=dowload_desc, execution_date=20220320T000000, start_date=20220321T095834, end_date=20220321T095834
[2022-03-21 09:58:34,841] {local_task_job.py:146} INFO - Task exited with return code 1
