[2022-03-20 20:57:20,893] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 20:57:20,903] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 20:57:20,904] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 20:57:20,904] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2022-03-20 20:57:20,904] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 20:57:20,918] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): prepare_insert> on 2022-03-19T00:00:00+00:00
[2022-03-20 20:57:20,922] {standard_task_runner.py:52} INFO - Started process 570 to run task
[2022-03-20 20:57:20,925] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'prepare_insert', '2022-03-19T00:00:00+00:00', '--job-id', '296', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmphhs09vto', '--error-file', '/tmp/tmpjlwg26u6']
[2022-03-20 20:57:20,926] {standard_task_runner.py:77} INFO - Job 296: Subtask prepare_insert
[2022-03-20 20:57:20,970] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.prepare_insert 2022-03-19T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-20 20:57:21,011] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=prepare_insert
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-19T00:00:00+00:00
[2022-03-20 20:57:21,012] {logging_mixin.py:104} INFO - /tmp/news_nvidia_2022-03-19_2022-03-20.sql
[2022-03-20 20:57:21,013] {python.py:118} INFO - Done. Returned value was: None
[2022-03-20 20:57:21,052] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=fetch_news, task_id=prepare_insert, execution_date=20220319T000000, start_date=20220320T205720, end_date=20220320T205721
[2022-03-20 20:57:21,119] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 20:57:21,150] {local_task_job.py:146} INFO - Task exited with return code 0
